server:
  port: 8022

spring:
  application:
    name: yhtian-spring-boot
  redis:
    port: 6379
    host: 127.0.0.1
    password: secret
    database: 0
    timeout: 2000

person:
  name: yhtian
  age: 19
  lists:
    - a1
    - a2
  maps:
    k1: v1
    k2: 12

  dog:
    name: gou
    age: 2
